version: '3.7'
services:
    postgresql:
      image: postgresql:12-alpine
      ports:
          - '3306:3306'
      volumes:
          - ./data:/var/lib/postgresql
      environment:
        - POSRGRESQL_DB=app
        - POSRGRESQL_USER=app
        - POSRGRESQL_PASSWORD=9mREsvXDs9Gk89Ef
