version: '3.7'
services:
    postgres:
      image: postgres:latest
      ports:
          - '3306:3306'
      volumes:
          - ./data:/var/lib/postgres
      environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
